language: node_js
node_js:
- '5.8'
services:
- postgresql
apt addons: 
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm run db-setup-travis
script: 
after_success: 
after_failure: 
before_deploy: 
after_deploy: 
after_script: 
deploy:
  provider: heroku
  api_key:
    - secure: MXRoHzKfKAQle6MAaRYKoYxNXZ8wE12dWz8ohz3cn0vpHd2rqtAW44jvPIApdIgnQl7x0D5+RdwAqJHeyaiQl0EXxWIK+/3G+L1s97agAu1ONHZmrsPlWQt3Ps+wpXhWm9yTgDK9r4vllQ0l9Eric08IJddbh53WNfpWCj8Qq1blJH7wLXcsvPAK94a2Kwyt1pSSHLsnGRjehCMCid2eK/KqIUwajTxNAESQiSng6dL8rlywF6SFKHQHyHCa6VK6KRU6bI9FrND0Q7NH/BmOlCL18HnULwAUEcYdYRxuCUdSRMva+3gcmieYTCkuIVhoFVufIAKOsJr0sJ1V5pir4vLgPICJNdVOnXa/CdzNcuQZJjYbTH6vTURQQp19/56zHGyWEtzPGTFpafoejj3HF2rR2PT74auUsOD/rz25CPR/aINSHl0T0IeMx/eAwR1eR2cWFoPCSQk2/p98l7xKhRZoDdX1LpW48D9noQxjEPhmZ+8rnyM0QNXNpTIxcHwhUpVhY3b6L1KC7rxgFYGP1WCAFxsWoty1NFzseCw2LYndhh2m/kR0uo5KoIPJxT1quLUOGDCn5FzXn1SWyemT4OuLOaRS7/0BE/Dw0aD+XQkeB1KxLPuLS7QAgYs/7p7BdM6KdCrVM5vpicRD7h5nHYBO/g0PCc0M0ZDfi0ln5oE=
  app: kitchengalactica
  on:
    repo: rompingstalactite/rompingstalactite
  run: 'npm start'
